version: '2'
services:
  apache:
    build: ./docker/apache/.
    volumes:
      - .:/var/www/code
    working_dir: /var/www/code
    ports:
      - "8081:80"
    environment:
      APACHE_LOG_DIR: '/var/log/apache2'
      DEBUG: 'true'
      TEST_MODE: 'local'
      DB_HOST: db
      DB_DATABASE: appetiser
      DB_USERNAME: appetiser
      DB_PASSWORD: appetiser
      DB_PORT: 3306
    links:
      - db
  db:
    # image: mysql:5.7
    build: ./docker/mysql/.
    restart: always
    # restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_USER: appetiser
      MYSQL_PASSWORD: appetiser
      MYSQL_DATABASE: appetiser
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/sql:/docker-entrypoint-initdb.d
      - ./docker/mysql/log:/var/log/mysql
    ports:
      - "33302:3306"
    command: mysqld --sql_mode=""
  node:
    build: ./docker/node/.
    working_dir: /app
    volumes:
      - .:/app
    links:
      - apache
    command: bash -c "ln -sf /node_modules node_modules && sleep infinity"
volumes:
  esdata1:
    driver: local